name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        default: '"stable"'

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(format('[{0}]', inputs.branch || '"1.2.0","1.2.x","1.4.2","1.4.x","1.6.2","1.6.x","2.0.0","2.0.x","stable","devel"')) }}

    name: 'nim-${{matrix.branch}}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.branch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          nim --version
          env TEST_LANG="c" nimble test
          env TEST_LANG="cpp" nimble test

