name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        default: stable

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
            TEST_LANG: c
          - os: linux
            cpu: amd64
            TEST_LANG: cpp
        branch: ${{ fromJSON(format('[{0}]', inputs.branch || '"1.2.x","1.4.x","1.6.x","2.0.x", "devel"')) }}
        include:
          - target:
              os: linux
            shell: bash
    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: 'nim-${{matrix.branch}}-${{ matrix.target.TEST_LANG }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.branch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          nim --version
          env TEST_LANG="${{ matrix.target.TEST_LANG }}" nimble test

